version: '3.3'

volumes:
  pg_database:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_database:/var/lib/postgresql/data
    restart: always

  backend:
    image: dm1triyden1senko/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always

  frontend:
    image: dm1triyden1senko/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
    depends_on:
      - db
      - backend

  nginx:
    image: nginx:1.19.3-alpine
    ports:
      - "10000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/usr/share/nginx/html
      - media:/usr/share/nginx/html/media
    depends_on:
      - backend
    restart: always
